### ISSUE TITLE
Shiny App crashes

### ISSUE THREAD

**Issue by mathan4stat** [rstudio/shiny#2118]
Shiny app crashes because of the following error message, even the simple template that RStudio makes available crashes

```
Warning: Error in safeFromJSON: Argument 'txt' is not a valid JSON string.
  [No stack trace available]
Error in safeFromJSON(charData, simplifyVector = FALSE) : 
  Argument 'txt' is not a valid JSON string.
Warning: Error in safeFromJSON: Argument 'txt' is not a valid JSON string.
  [No stack trace available]
Error in safeFromJSON(charData, simplifyVector = FALSE) : 
  Argument 'txt' is not a valid JSON string.
```

Any help on this?

**Comment by jcheng5** [comment]
What does devtools::session_info() give you?

**Comment by mathan4stat** [comment]
The result of `devtools::session_info() ` is below
```
> devtools::session_info() 
Session info ------------------------------------------------------------------------------------------------------------------------
setting  value                       
 version  R version 3.4.1 (2017-06-30)
system   x86_64, linux-gnu           
 ui       RStudio (1.1.447)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2018-07-05                  

Packages ----------------------------------------------------------------------------------------------------------------------------
package   * version    date       source                          
 base      * 3.4.1      2017-06-30 local                           
 compiler    3.4.1      2017-06-30 local                           
 datasets  * 3.4.1      2017-06-30 local                           
 devtools    1.13.3     2017-08-02 CRAN (R 3.4.1)                  
 digest      0.6.15     2018-01-28 cran (@0.6.15)                  
 graphics  * 3.4.1      2017-06-30 local                           
 grDevices * 3.4.1      2017-06-30 local                           
 htmltools   0.3.6      2017-04-28 CRAN (R 3.4.1)                  
 httpuv      1.4.4.1    2018-06-18 CRAN (R 3.4.1)                  
 jsonlite    1.5        2017-06-01 CRAN (R 3.4.1)                  
 later       0.7.3      2018-06-08 CRAN (R 3.4.1)                  
 magrittr    1.5        2014-11-22 CRAN (R 3.4.1)                  
 memoise     1.1.0      2017-04-21 CRAN (R 3.4.1)                  
 methods   * 3.4.1      2017-06-30 local                           
 mime        0.5        2016-07-07 CRAN (R 3.4.1)                  
 promises    1.0.1      2018-04-13 CRAN (R 3.4.1)                  
 R6          2.2.2      2017-06-17 CRAN (R 3.4.1)                  
 Rcpp        0.12.17    2018-05-18 CRAN (R 3.4.1)                  
 shiny     * 1.1.0      2018-05-17 CRAN (R 3.4.1)                  
 stats     * 3.4.1      2017-06-30 local                           
 tools       3.4.1      2017-06-30 local                           
 utils     * 3.4.1      2017-06-30 local                           
 withr       2.1.1.9000 2018-02-12 Github (jimhester/withr@df18523)
xtable      1.8-2      2016-02-05 CRAN (R 3.4.1)                  
 yaml        2.1.16     2017-12-12 cran (@2.1.16)      

```

**Comment by JeremyBesson** [comment]
Same error for me after an upgrade from R3.2 to R3.4.
The error occur only with firefox and some recent chrome version.

It seem to be linked with the version of rjson:
when rjson is in 0.2.20 version the error appear 
when rjson is in 0.2.18 version the error doesn't appear 

I currently try do a test with an R in 3.4 version and downgrade rjson. 
I'll tell you if this is the root cause.

**Comment by wch** [comment]
@JeremyBesson Shiny does not use rjson, so it would be very surprising if the error was related to rjson.


@mathan4stat What does it print out if you run this first, and then run the app?

```R
options(error = traceback)
```

**Comment by jcheng5** [comment]
And does it help if you do `devtools::install_version("httpuv", "1.4.3")` and restart your R session?

**Comment by mathan4stat** [comment]
@wch Please see the logs below. Thanks for your support here.

```
> options(error = traceback)
> runApp()

Listening on http://127.0.0.1:5875

12: .Call("_later_execCallbacks", PACKAGE = "later", timeoutSecs)
11: execCallbacks(timeoutSecs)
10: run_now(timeoutMs/1000)
9: service(timeout)
8: serviceApp()
7: ..stacktracefloor..(serviceApp())
6: withCallingHandlers(expr, error = doCaptureStack)
5: globals$domain$wrapSync(expr)
4: promises::with_promise_domain(createStackTracePromiseDomain(), 
       expr)
3: captureStackTraces({
       while (!.globals$stopped) {
           ..stacktracefloor..(serviceApp())
           Sys.sleep(0.001)
       }
   })
2: ..stacktraceoff..(captureStackTraces({
       while (!.globals$stopped) {
           ..stacktracefloor..(serviceApp())
           Sys.sleep(0.001)
       }
   }))
1: runApp()

No traceback available
```

**Comment by mathan4stat** [comment]
@jcheng5 I was unable to install 

```
g++: error trying to exec 'cc1plus': execvp: No such file or directory
make: *** [RcppExports-legacy.o] Error 1
ERROR: compilation failed for package ‘httpuv’
* removing ‘/local/home/user/R/x86_64-redhat-linux-gnu-library/3.4/httpuv’
Installation failed: Command failed (1)
```

**Comment by JeremyBesson** [comment]
@jcheng5 You mean instead of a more recent version like httpuv 1.4.4.1 ?

**Comment by JeremyBesson** [comment]
@jcheng5 You right this is exactly the cause. 
I've removed httpuv 1.4.4.1 and reinstalled it with devtools::install_version("httpuv", "1.4.3")
And now shiny apps work again.

**Comment by mathan4stat** [comment]
It works fine on Chrome (Version 67.0.3396.87 (Official Build) (64-bit)). It looks like browser problem hence closing this issue. Thanks for the support.
